name = "diw_armor_plates"
prefix = "diw_armor_plates"
author = "diwako"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3
version = "0.7.0"
exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]
reuse_private_key = false
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE",
    "readme.txt",
    "readme.md"
]
include = ["./include"]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

check = [
    "!version_set",
    "!compile_scripts"
]

postbuild = [
    "!version_unset",
    "!remove_compiled_scripts"
]

releasebuild = [
    "!version_set_release",
    "@zip @diw_armor_plates_{{semver.major}}_{{semver.minor}}_{{semver.patch}}"
]

[header_exts]
version = "{{version}}_{{git \"id 8\"}}"

[scripts.version_set]
steps_linux = [
    "echo 'Setting version'",
    "sed -i -r -s 's/#define MAJOR 0/#define MAJOR {{semver.major}}/g' addons/main/script_version.hpp",
    "sed -i -r -s 's/#define MINOR 0/#define MINOR {{semver.minor}}/g' addons/main/script_version.hpp",
    "sed -i -r -s 's/#define PATCHLVL 0/#define PATCHLVL {{semver.patch}}/g' addons/main/script_version.hpp",
]
steps_windows = [
    "echo 'Setting version'",
    "powershell -Command foreach ($f in 'addons/main/script_version.hpp') {(Get-Content $f) -replace '#define MAJOR 0', '#define MAJOR {{semver.major}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/main/script_version.hpp') {(Get-Content $f) -replace '#define MINOR 0', '#define MINOR {{semver.minor}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/main/script_version.hpp') {(Get-Content $f) -replace '#define PATCHLVL 0', '#define PATCHLVL {{semver.patch}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
]
only_release = true
show_output = true

[scripts.version_unset]
steps_linux = [
    "echo 'Unsetting version'",
    "sed -i -r -s 's/#define MAJOR {{semver.major}}/#define MAJOR 0/g' addons/main/script_version.hpp",
    "sed -i -r -s 's/#define MINOR {{semver.minor}}/#define MINOR 0/g' addons/main/script_version.hpp",
    "sed -i -r -s 's/#define PATCHLVL {{semver.patch}}/#define PATCHLVL 0/g' addons/main/script_version.hpp",
]
steps_windows = [
    "echo 'Unsetting version'",
    "powershell -Command foreach ($f in 'addons/main/script_version.hpp') {(Get-Content $f) -replace '#define MAJOR {{semver.major}}', '#define MAJOR 0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/main/script_version.hpp') {(Get-Content $f) -replace '#define MINOR {{semver.minor}}', '#define MINOR 0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/main/script_version.hpp') {(Get-Content $f) -replace '#define PATCHLVL {{semver.patch}}', '#define PATCHLVL 0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
]
only_release = true
show_output = true

[scripts.version_set_release]
steps_linux = [
    "sed -i -r -s 's/{version}/{{semver.major}}.{{semver.minor}}.{{semver.patch}}/g' releases/{{semver.major}}.{{semver.minor}}.{{semver.patch}}/@diw_armor_plates/mod.cpp",
]
steps_windows = [
    "powershell -Command foreach ($f in 'releases/{{semver.major}}.{{semver.minor}}.{{semver.patch}}/@diw_armor_plates/mod.cpp') {(Get-Content $f) -replace '{version}', '{{semver.major}}.{{semver.minor}}.{{semver.patch}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
]
only_release = true
show_output = true

[scripts.compile_scripts]
steps_windows = [
    "echo 'Compile Arma Scripts'",
    "ArmaScriptCompiler.exe"
]

steps_linux = [
    "echo 'Compiling Arma Scripts does not work yet on Linux'"
]
only_release = true
# only_release = false
show_output = true

[scripts.remove_compiled_scripts]
steps_windows = [
    "echo 'remove Compiled Scripts'",
    "powershell -Command Remove-Item './addons/*' -Recurse -Include *.sqfc"
]
steps_linux = [
    "echo 'Compiling Arma Scripts does not work yet on Linux'"
]
only_release = false
show_output = true
