class CfgMovesBasic {
    class ManActions {
        GVAR(addPlate_base)= QGVAR(addPlate_base);
        GVAR(addPlate_2_0)= QGVAR(addPlate_2_0);
        GVAR(addPlate_3_0)= QGVAR(addPlate_3_0);
        GVAR(addPlate_4_0)= QGVAR(addPlate_4_0);
        GVAR(addPlate_5_0)= QGVAR(addPlate_5_0);
        GVAR(addPlate_6_0)= QGVAR(addPlate_6_0);
        GVAR(addPlate_7_0)= QGVAR(addPlate_7_0);
        GVAR(addPlate_8_0)= QGVAR(addPlate_8_0);
        GVAR(addPlate_9_0)= QGVAR(addPlate_9_0);
        GVAR(addPlate_10_0)= QGVAR(addPlate_10_0);
        GVAR(addPlate_11_0)= QGVAR(addPlate_11_0);
        GVAR(addPlate_12_0)= QGVAR(addPlate_12_0);
        GVAR(addPlate_13_0)= QGVAR(addPlate_13_0);
        GVAR(addPlate_14_0)= QGVAR(addPlate_14_0);
        GVAR(addPlate_15_0)= QGVAR(addPlate_15_0);
        GVAR(addPlate_16_0)= QGVAR(addPlate_16_0);
        GVAR(addPlate_2_1)= QGVAR(addPlate_2_1);
        GVAR(addPlate_3_1)= QGVAR(addPlate_3_1);
        GVAR(addPlate_4_1)= QGVAR(addPlate_4_1);
        GVAR(addPlate_5_1)= QGVAR(addPlate_5_1);
        GVAR(addPlate_6_1)= QGVAR(addPlate_6_1);
        GVAR(addPlate_7_1)= QGVAR(addPlate_7_1);
        GVAR(addPlate_8_1)= QGVAR(addPlate_8_1);
        GVAR(addPlate_9_1)= QGVAR(addPlate_9_1);
        GVAR(addPlate_10_1)= QGVAR(addPlate_10_1);
        GVAR(addPlate_11_1)= QGVAR(addPlate_11_1);
        GVAR(addPlate_12_1)= QGVAR(addPlate_12_1);
        GVAR(addPlate_13_1)= QGVAR(addPlate_13_1);
        GVAR(addPlate_14_1)= QGVAR(addPlate_14_1);
        GVAR(addPlate_15_1)= QGVAR(addPlate_15_1);
        GVAR(addPlate_16_1)= QGVAR(addPlate_16_1);
        GVAR(addPlate_2_2)= QGVAR(addPlate_2_2);
        GVAR(addPlate_3_2)= QGVAR(addPlate_3_2);
        GVAR(addPlate_4_2)= QGVAR(addPlate_4_2);
        GVAR(addPlate_5_2)= QGVAR(addPlate_5_2);
        GVAR(addPlate_6_2)= QGVAR(addPlate_6_2);
        GVAR(addPlate_7_2)= QGVAR(addPlate_7_2);
        GVAR(addPlate_8_2)= QGVAR(addPlate_8_2);
        GVAR(addPlate_9_2)= QGVAR(addPlate_9_2);
        GVAR(addPlate_10_2)= QGVAR(addPlate_10_2);
        GVAR(addPlate_11_2)= QGVAR(addPlate_11_2);
        GVAR(addPlate_12_2)= QGVAR(addPlate_12_2);
        GVAR(addPlate_13_2)= QGVAR(addPlate_13_2);
        GVAR(addPlate_14_2)= QGVAR(addPlate_14_2);
        GVAR(addPlate_15_2)= QGVAR(addPlate_15_2);
        GVAR(addPlate_16_2)= QGVAR(addPlate_16_2);
        GVAR(stopGesture) = QGVAR(stopGesture);
    };
    class Actions {
        class Default;
        class NoActions: ManActions {
            GVAR(addPlate_base)[]= {QGVAR(addPlate_base), "Gesture"};
            GVAR(addPlate_2_0)[]= {QGVAR(addPlate_2_0), "Gesture"};
            GVAR(addPlate_3_0)[]= {QGVAR(addPlate_3_0), "Gesture"};
            GVAR(addPlate_4_0)[]= {QGVAR(addPlate_4_0), "Gesture"};
            GVAR(addPlate_5_0)[]= {QGVAR(addPlate_5_0), "Gesture"};
            GVAR(addPlate_6_0)[]= {QGVAR(addPlate_6_0), "Gesture"};
            GVAR(addPlate_7_0)[]= {QGVAR(addPlate_7_0), "Gesture"};
            GVAR(addPlate_8_0)[]= {QGVAR(addPlate_8_0), "Gesture"};
            GVAR(addPlate_9_0)[]= {QGVAR(addPlate_9_0), "Gesture"};
            GVAR(addPlate_10_0)[]= {QGVAR(addPlate_10_0), "Gesture"};
            GVAR(addPlate_11_0)[]= {QGVAR(addPlate_11_0), "Gesture"};
            GVAR(addPlate_12_0)[]= {QGVAR(addPlate_12_0), "Gesture"};
            GVAR(addPlate_13_0)[]= {QGVAR(addPlate_13_0), "Gesture"};
            GVAR(addPlate_14_0)[]= {QGVAR(addPlate_14_0), "Gesture"};
            GVAR(addPlate_15_0)[]= {QGVAR(addPlate_15_0), "Gesture"};
            GVAR(addPlate_16_0)[]= {QGVAR(addPlate_16_0), "Gesture"};
            GVAR(addPlate_2_1)[]= {QGVAR(addPlate_2_1), "Gesture"};
            GVAR(addPlate_3_1)[]= {QGVAR(addPlate_3_1), "Gesture"};
            GVAR(addPlate_4_1)[]= {QGVAR(addPlate_4_1), "Gesture"};
            GVAR(addPlate_5_1)[]= {QGVAR(addPlate_5_1), "Gesture"};
            GVAR(addPlate_6_1)[]= {QGVAR(addPlate_6_1), "Gesture"};
            GVAR(addPlate_7_1)[]= {QGVAR(addPlate_7_1), "Gesture"};
            GVAR(addPlate_8_1)[]= {QGVAR(addPlate_8_1), "Gesture"};
            GVAR(addPlate_9_1)[]= {QGVAR(addPlate_9_1), "Gesture"};
            GVAR(addPlate_10_1)[]= {QGVAR(addPlate_10_1), "Gesture"};
            GVAR(addPlate_11_1)[]= {QGVAR(addPlate_11_1), "Gesture"};
            GVAR(addPlate_12_1)[]= {QGVAR(addPlate_12_1), "Gesture"};
            GVAR(addPlate_13_1)[]= {QGVAR(addPlate_13_1), "Gesture"};
            GVAR(addPlate_14_1)[]= {QGVAR(addPlate_14_1), "Gesture"};
            GVAR(addPlate_15_1)[]= {QGVAR(addPlate_15_1), "Gesture"};
            GVAR(addPlate_16_1)[]= {QGVAR(addPlate_16_1), "Gesture"};
            GVAR(addPlate_2_2)[]= {QGVAR(addPlate_2_2), "Gesture"};
            GVAR(addPlate_3_2)[]= {QGVAR(addPlate_3_2), "Gesture"};
            GVAR(addPlate_4_2)[]= {QGVAR(addPlate_4_2), "Gesture"};
            GVAR(addPlate_5_2)[]= {QGVAR(addPlate_5_2), "Gesture"};
            GVAR(addPlate_6_2)[]= {QGVAR(addPlate_6_2), "Gesture"};
            GVAR(addPlate_7_2)[]= {QGVAR(addPlate_7_2), "Gesture"};
            GVAR(addPlate_8_2)[]= {QGVAR(addPlate_8_2), "Gesture"};
            GVAR(addPlate_9_2)[]= {QGVAR(addPlate_9_2), "Gesture"};
            GVAR(addPlate_10_2)[]= {QGVAR(addPlate_10_2), "Gesture"};
            GVAR(addPlate_11_2)[]= {QGVAR(addPlate_11_2), "Gesture"};
            GVAR(addPlate_12_2)[]= {QGVAR(addPlate_12_2), "Gesture"};
            GVAR(addPlate_13_2)[]= {QGVAR(addPlate_13_2), "Gesture"};
            GVAR(addPlate_14_2)[]= {QGVAR(addPlate_14_2), "Gesture"};
            GVAR(addPlate_15_2)[]= {QGVAR(addPlate_15_2), "Gesture"};
            GVAR(addPlate_16_2)[]= {QGVAR(addPlate_16_2), "Gesture"};
            GVAR(stopGesture)[] = {QGVAR(stopGesture), "Gesture"};
        };
    };
};

#define ADDPLATE(SECONDS,HEADBOBSTRENGTH) \
    class DOUBLES(ADDON,TRIPLES(addPlate,SECONDS,HEADBOBSTRENGTH)): GVAR(addPlate_base) { \
        speed = QUOTE(-SECONDS + 0.5); headBobStrength = QUOTE(-HEADBOBSTRENGTH * 0.25); \
    }

class CfgGesturesMale {
    class Default;
    class States {
        class GVAR(addPlate_base): Default {
            speed = 0;
            looped = 0;
            file = QPATHTOF(anims\add_plate.rtm);
            mask = "handsWeapon";
            headBobStrength = 0.0;
            headBobMode = 2;
            disableWeapons = 1;
            interpolationRestart = 2;
            leftHandIKCurve[] = {0.01,1,0.1,0,0.94,0,0.98,1};
            rightHandIKBeg = 1;
            leftHandIKEnd = 1;
            rightHandIKCurve[] = {1};
            weaponIK = 1;
            canReload = 0;
        };
        ADDPLATE(2,0);
        ADDPLATE(3,0);
        ADDPLATE(4,0);
        ADDPLATE(5,0);
        ADDPLATE(6,0);
        ADDPLATE(7,0);
        ADDPLATE(8,0);
        ADDPLATE(9,0);
        ADDPLATE(10,0);
        ADDPLATE(11,0);
        ADDPLATE(12,0);
        ADDPLATE(13,0);
        ADDPLATE(14,0);
        ADDPLATE(15,0);
        ADDPLATE(16,0);
        ADDPLATE(2,1);
        ADDPLATE(3,1);
        ADDPLATE(4,1);
        ADDPLATE(5,1);
        ADDPLATE(6,1);
        ADDPLATE(7,1);
        ADDPLATE(8,1);
        ADDPLATE(9,1);
        ADDPLATE(10,1);
        ADDPLATE(11,1);
        ADDPLATE(12,1);
        ADDPLATE(13,1);
        ADDPLATE(14,1);
        ADDPLATE(15,1);
        ADDPLATE(16,1);
        ADDPLATE(2,2);
        ADDPLATE(3,2);
        ADDPLATE(4,2);
        ADDPLATE(5,2);
        ADDPLATE(6,2);
        ADDPLATE(7,2);
        ADDPLATE(8,2);
        ADDPLATE(9,2);
        ADDPLATE(10,2);
        ADDPLATE(11,2);
        ADDPLATE(12,2);
        ADDPLATE(13,2);
        ADDPLATE(14,2);
        ADDPLATE(15,2);
        ADDPLATE(16,2);
        class GestureNod;
        class GVAR(stopGesture): GestureNod {
            file = "a3\anims_f\data\anim\sdr\gst\gestureEmpty.rtm";
            disableWeapons = 0;
            disableWeaponsLong = 0;
            enableOptics = 1;
            mask = "empty";
        };
    };
};
