name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT check
        run: hemtt check --pedantic
      - name: Validate Config
        run: python3 tools/config_style_checker.py
      - name: Check for BOM
        uses: arma-actions/bom-check@master
      - name: .editorconfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT build
        run: hemtt build
      - name: Upload Build
        uses: actions/upload-artifact@v7
        with:
          name: "@diw_armor_plates"
          path: ".hemttout/build/*"
