name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
    - name: .editorconfig Checker
      uses: editorconfig-checker/action-editorconfig-checker@main
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
    - name: Run Stringtable Checker
      run: cd tools/nodejs_tools && npm i &> /dev/null && cd ../../ && node tools/nodejs_tools/stringTableChecker.js
    - name: Check Functions
      run: node tools/nodejs_tools/prepchecker.js

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Lint (sqflint)
      uses: jokoho48/sqflint@master
      continue-on-error: true # No failure due to many false-positives
    - uses: actions/upload-artifact@v4
      with:
       name: 'sqfLint Log'
       path: 'sqf.log'
    - name: Validate SQFLinter Logs
      run: python3 tools/sqf_linter_LogChecker.py

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
      - name: Setup Node tools
        run: cd tools/nodejs_tools && npm i &> /dev/null && cd ../../
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Set Build Version
        run: node tools/nodejs_tools/gitversionsetter.js
      - name: Run HEMTT build
        run: hemtt release
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: '@diw_armor_plates'
          path: '.hemttout/release/*'
